services:
  - type: web
    name: vj-stream-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TMDB_LANGUAGE
        value: es-ES
      - key: TMDB_API_KEY
        sync: false
      - key: REALDEBRID_API_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
